name       : mate-backgrounds
version    : 1.14.0
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-backgrounds-1.14.0.tar.xz : 1e01411969496e766db479b53ea1caa66ae7e3b350d011aa112840dcffd30751
license    : GPL-2.0
component  : desktop.mate
summary    : Background images for the MATE desktop
description: |
    Background images and data for MATE. The MATE backgrounds are a fork of GNOME backgrounds.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
