name       : mate-backgrounds
version    : 1.24.1
release    : 7
source     :
    - https://github.com/mate-desktop/mate-backgrounds/archive/v1.24.1.tar.gz : df6fe2173a8ea482b509cd7e186bd98c7075a6fcee9d1bf81541d5f426f5cdf9
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Background images for the MATE desktop
description: |
    Background images and data for MATE. The MATE backgrounds are a fork of GNOME backgrounds.
builddeps  :
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
