name       : mate-backgrounds
version    : 1.26.0
release    : 9
source     :
    - https://github.com/mate-desktop/mate-backgrounds/releases/download/v1.26.0/mate-backgrounds-1.26.0.tar.xz : 0dc9127224ae1573301cfa0aaa6c6262827072d2bf6e5c67c9e1aae19f85e90c
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Background images for the MATE desktop
description: |
    Background images and data for MATE. The MATE backgrounds are a fork of GNOME backgrounds.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
