name       : mate-backgrounds
version    : 1.18.0
release    : 3
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-backgrounds-1.18.0.tar.xz : f103d38898cc088608c813d732e4681fd6a8b9cf2a9564b9d057461da59e081b
license    : GPL-2.0
component  : desktop.mate
summary    : Background images for the MATE desktop
description: |
    Background images and data for MATE. The MATE backgrounds are a fork of GNOME backgrounds.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
