name       : mate-backgrounds
version    : 1.20.0
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-backgrounds-1.20.0.tar.xz : 57b2127cba9233aef1db6fa3ecc85b2c8422e6d26565c797701079003893965d
license    : GPL-2.0
component  : desktop.mate
summary    : Background images for the MATE desktop
description: |
    Background images and data for MATE. The MATE backgrounds are a fork of GNOME backgrounds.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
