name       : mate-backgrounds
version    : 1.24.2
release    : 8
source     :
    - https://github.com/mate-desktop/mate-backgrounds/releases/download/v1.24.2/mate-backgrounds-1.24.2.tar.xz : e5bea10c346bf527508fe4c94e4b34785434dc5cf93d72571425b751e916abc7
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Background images for the MATE desktop
description: |
    Background images and data for MATE. The MATE backgrounds are a fork of GNOME backgrounds.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
